config/routes.rb
Rails.application.routes.draw do

  post "/login",         to: 'sessions#create',     as: :login
  post "/logout",        to: 'sessions#destroy',    as: :logout

  get "/users/new",      to: 'users#new',           as: :new_user
  post "/users/new",     to: 'users#create'
  get "/dash",           to: 'users#show',          as: :my_account

  get "maps/:id/add_room",   to: 'maps#add_room',  as: :new_room
  post "maps/:id/add_room",   to: 'rooms#create'

  get "rooms/:id/add_item",   to: 'rooms#add_item',  as: :new_item
  post "rooms/:id/add_item",   to: 'items#create'
  get "rooms/:id/add_path",   to: 'rooms#add_path',  as: :new_path
  post "rooms/:id/add_path",   to: 'paths#create'

  resources :maps
  resources :rooms
  resources :items

  root 'pages#home'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :inventory, polymorphic: true
end

app/models/map.rb
class Map < ActiveRecord::Base
  has_many :rooms
  belongs_to :user
  has_one :player, through: :rooms

  validates :name, presence: true, uniqueness: true
  validates :desc, :user_id, presence: true

end

app/models/path.rb
class Path < ActiveRecord::Base
  belongs_to :room

  validates :direction, :destination, :room_id, presence: true

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
  has_many :items, as: :inventory
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :map
  has_one :player
  has_many :items, as: :inventory
  has_many :paths

  validates :name, :full_desc, :short_desc, :map_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :maps
  has_many :players

   validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def path_destination(path)
    Room.find(path.destination)
  end
  helper_method :path_destination

  def reverse_direction(direction)
    case direction
    when "north"
      "south"
    when "northeast"
      "southwest"
    when "east"
      "west"
    when "southeast"
      "northwest"
    when "south"
      "north"
    when "southwest"
      "northeast"
    when "west"
      "east"
    when "northwest"
      "southeast"
    else
      raise "Not a recognized direction"
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    @item = Item.new(item_params)
    @room = Room.find(params[:item][:inventory_id])
    if @item.save
      redirect_to @room, notice: "Item created!"
    else
      render 'rooms/show'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  private

  def item_params
    params.require(:item).permit(:name, :desc, :inventory_type, :inventory_id)
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def new
    @map = Map.new
  end

  def create
    @map = Map.new(map_params)
    if @map.save
      redirect_to current_user
    else
      render "new"
    end
  end

  def show
    @map = Map.find(params[:id])
  end

  def add_room
    @map = Map.find(params[:id])
    @room = Room.new
    render :show
  end

  private

  def map_params
    params.require(:map).permit(:name, :desc)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController

  def create
    @path = Path.new(path_params)
    @room = Room.find(params[:path][:room_id])
    if @path.save
      matching_path(@path)
      redirect_to @room, notice: "Path added!"
    else
      render 'maps/show'
    end
  end

  #maybe allow user to select if path is one-way or two-way (checkbox?)

  def matching_path(path1)
    direction = reverse_direction(path1.direction)
    destination = path1.room_id
    room_id = path_destination(path1).id
    Path.create(direction: direction, destination: destination, room_id: room_id)
  end

  #some kind of catch for if either path fails to save??

  def show
    @path = Path.find(params[:id])
  end

  private

  def path_params
    params.require(:path).permit(:direction, :destination, :room_id, :available)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def create
    @room = Room.new(room_params)
    @map = Map.find(params[:room][:map_id])
    if @room.save
      redirect_to @map, notice: "Room created!"
    else
      render 'maps/show'
    end
  end

  def show
    @room = Room.find(params[:id])
  end

  def add_item
    @room = Room.find(params[:id])
    @item = Item.new
    render :show
  end

  def add_path
    @room = Room.find(params[:id])
    @path = Path.new
    render :show
  end


  private

  def room_params
    params.require(:room).permit(:name, :short_desc, :full_desc, :map_id)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(name: params[:name])       #find user by name typed in
    if user && user.authenticate(params[:password]) # if user was found matching that name and if password
                                                    # matches with authenticate
      session[:user_id] = user.id                   #store user id to session
      redirect_to root_path, notice: "Logged in!"

    else
      flash.now.alert = "Email or password is invalid"
      render "pages/home"
    end
  end

  def destroy #creates logout function
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged Out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_helper.rb
module ErrorHelper

  def error_message(obj)
    if obj.errors.any?
      html =  "<ul class='error_messages'>"
      obj.errors.each do |column_name, message|
        html += "<li> <strong>" + column_name.to_s.capitalize + "</strong> " + message + "</li>"
      end
      html += "</ul>"
      html.html_safe
    end
  end


end

app/helpers/user_helper.rb
module UserHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Textgame</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'  %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |name, msg| %> <!-- flash message provided by rails-->
  <%= content_tag :div, msg, id: "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/maps/new.html.erb
<h1> Create A New Map </h1>

<%= bootstrap_form_for @map, url: new_map_path do |f| %> <!-- form_for user model -->
   <%= f.hidden_field :user_id, value: current_user.id %>

      <div class="field">
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.text_area :desc %>
      </div>
    <div class="actions"><%= f.submit  %></div>
<% end %>

app/views/maps/show.html.erb
<h1><%= @map.name %> </h1>

<section>
  <%= @map.desc %>
</section>

<section>
  <h3> Rooms </h3>
  <% @map.rooms.each do |room| %>
    <div class = "room-link">
      <%=link_to room.name, room %>
    </div>
  <% end %>

  <% if @room %>
    <%= bootstrap_form_for @room, url: new_room_path do |f| %>
       <%= f.hidden_field :map_id, value: @map.id %>

          <div class="field">
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.text_field :short_desc %>
          </div>
          <div class="field">
            <%= f.text_area :full_desc %>
          </div>
        <div class="actions"><%= f.submit  %></div>
    <% end %>
  <% else %>
    <%= button_to "Add a Room", new_room_path, method: :get %>
  <% end %>
</section>

app/views/pages/home.html.erb
<h1> Welcome! </h1>

<% if current_user %>
You are logged in as <%= current_user.name %>.
<%= button_to "Log out", logout_path %>

<% else %>

<section>

    You are not currently logged in. Please log in!

    <%= bootstrap_form_tag url: login_path do |f| %>
    <%= f.text_field :name %>
    <%= f.password_field :password %>
    <%= f.submit "Log In" %>

    <% end %>
</section>

<%= button_to "Create an Account", new_user_path, method: :get %>

<% end %>

app/views/rooms/show.html.erb
<h1><%= @room.name %> </h1>

<section>
  Description: <%= @room.full_desc %>
</section>

<section>
  Map: <%=link_to @room.map.name, @room.map %>
</section>

<section>
  <h3> Items </h3>
    <% @room.items.each do |item| %>
      <div class = "item-link">
        <%= link_to item.name, item %>
      </div>
    <% end %>
</section>

<section>
  <h3> Paths </h3>
    <% @room.paths.each do |path| %>
      <div>
        <%= path.direction %>:
        <%= link_to path_destination(path).name, path_destination(path) %>
      </div>
    <% end %>
</section>

<section>
  <% if @path %>
    <%= bootstrap_form_for @path, url: new_path_path do |f| %>
      <%= f.hidden_field :room_id, value: @room.id %>
      <%= f.text_field :direction %>
      <%= f.collection_select :destination, @room.map.rooms, :id, :name %>
      <%= f.submit %>
    <% end %>

  <% else %>
    <%= button_to "Add a Path", new_path_path, method: :get %>
  <% end %>

</section>

<section>

  <% if @item %>
    <%= bootstrap_form_for @item, url: new_item_path do |f| %>
       <%= f.hidden_field :inventory_id, value: @room.id %>
       <%= f.hidden_field :inventory_type, value: "Room" %>

          <div class="field">
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.text_area :desc %>
          </div>
        <div class="actions"><%= f.submit  %></div>
    <% end %>
  <% else %>
    <%= button_to "Add an Item", new_item_path, method: :get %>
  <% end %>
</section>

app/views/users/new.html.erb
<h1> Create An Account </h1>

<%= bootstrap_form_for @user, url: new_user_path do |f| %> <!-- form_for user model -->

      <div class="field">
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.password_field :password_confirmation %>
      </div>
    <div class="actions"><%= f.submit  %></div>
<% end %>

app/views/users/show.html.erb
<h1> <%= current_user.name %>'s Account </h1>

<% unless current_user.maps.empty? %>
  <h2>My Maps:</h2>
  <% current_user.maps.each do |map| %>
    <%=button_to map.name, map, method: :get %>
  <% end %>
<% else %>
  You don't have any maps yet :(

<% end %>
<%= button_to "Create a New Map", new_map_path, method: :get %>